'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating IT solutions using the AI assistant QASA.
 *
 * The flow takes an IT problem description as input and returns a set of potential solutions generated by a language model.
 *
 * @file        ai-qasa-content-generation.ts
 * @exports   generateSolutions - The function to generate IT solutions.
 * @exports   GenerateSolutionsInput - The input type for the generateSolutions function.
 * @exports   GenerateSolutionsOutput - The output type for the generateSolutions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema
const GenerateSolutionsInputSchema = z.object({
  problemDescription: z.string().describe('A description of the IT problem.'),
});

export type GenerateSolutionsInput = z.infer<typeof GenerateSolutionsInputSchema>;

// Define the output schema
const GenerateSolutionsOutputSchema = z.object({
  solutions: z.array(z.string()).describe('A list of potential solutions to the IT problem.'),
});

export type GenerateSolutionsOutput = z.infer<typeof GenerateSolutionsOutputSchema>;

// Define the flow
const generateSolutionsFlow = ai.defineFlow(
  {
    name: 'generateSolutionsFlow',
    inputSchema: GenerateSolutionsInputSchema,
    outputSchema: GenerateSolutionsOutputSchema,
  },
  async input => {
    const {output} = await generateSolutionsPrompt(input);
    return output!;
  }
);

// Define the prompt
const generateSolutionsPrompt = ai.definePrompt({
  name: 'generateSolutionsPrompt',
  input: {schema: GenerateSolutionsInputSchema},
  output: {schema: GenerateSolutionsOutputSchema},
  prompt: `You are QASA, an AI assistant that helps CTOs generate potential solutions to IT problems.

  Given the following IT problem description, generate a list of potential solutions.

  Problem Description: {{{problemDescription}}}

  Solutions:`, // Ensure the prompt expects a list of solutions.
});

/**
 * Generates potential solutions to an IT problem using the generateSolutionsFlow.
 *
 * @param input - The input object containing the IT problem description.
 * @returns A promise that resolves to the output object containing a list of potential solutions.
 */
export async function generateSolutions(input: GenerateSolutionsInput): Promise<GenerateSolutionsOutput> {
  return generateSolutionsFlow(input);
}
